export const ADD_SIGNUP_REQUEST = 'ADD_SIGNUP_REQUEST';
export const ADD_SIGNUP_SUCCEED = 'ADD_SIGNUP_SUCCEED';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';

export const GET_SIGNIN_REQUEST = 'GET_SIGNIN_REQUEST';
export const GET_SIGNIN_SUCCEED = 'GET_SIGNIN_SUCCEED';

export const GET_SIGNOUT_REQUEST = 'GET_SIGNOUT_REQUEST';
export const GET_SIGNOUT_SUCCEED = 'GET_SIGNOUT_SUCCEED';

export const SHOW_MESSAGE = 'SHOW_MESSAGE';